// Mocks generated by Mockito 5.2.0 from annotations
// in homsai/test/util/light/light.dart.
// Do not manually edit this file.

import 'package:homsai/business/light/light.repository.dart' as _i4;
import 'package:homsai/datastore/models/entity/base/base.entity.dart' as _i6;
import 'package:homsai/datastore/models/entity/light/light.entity.dart' as _i5;
import 'package:homsai/datastore/remote/websocket/home_assistant.broker.dart'
    as _i3;
import 'package:homsai/datastore/remote/websocket/home_assistant_websocket.interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeHomeAssistantWebSocketInterface_0 extends _i1.Fake
    implements _i2.HomeAssistantWebSocketInterface {}

class _FakeHomeAssistantBroker_1 extends _i1.Fake
    implements _i3.HomeAssistantBroker {}

/// A class which mocks [LightRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLightRepository extends _i1.Mock implements _i4.LightRepository {
  MockLightRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeAssistantWebSocketInterface get webSocket =>
      (super.noSuchMethod(Invocation.getter(#webSocket),
              returnValue: _FakeHomeAssistantWebSocketInterface_0())
          as _i2.HomeAssistantWebSocketInterface);
  @override
  set webSocket(_i2.HomeAssistantWebSocketInterface? _webSocket) =>
      super.noSuchMethod(Invocation.setter(#webSocket, _webSocket),
          returnValueForMissingStub: null);
  @override
  _i3.HomeAssistantBroker get homeAssistantBroker => (super.noSuchMethod(
      Invocation.getter(#homeAssistantBroker),
      returnValue: _FakeHomeAssistantBroker_1()) as _i3.HomeAssistantBroker);
  @override
  set homeAssistantBroker(_i3.HomeAssistantBroker? _homeAssistantBroker) =>
      super.noSuchMethod(
          Invocation.setter(#homeAssistantBroker, _homeAssistantBroker),
          returnValueForMissingStub: null);
  @override
  void toggle(_i5.LightEntity? light) =>
      super.noSuchMethod(Invocation.method(#toggle, [light]),
          returnValueForMissingStub: null);
  @override
  void turnOff(_i5.LightEntity? light) =>
      super.noSuchMethod(Invocation.method(#turnOff, [light]),
          returnValueForMissingStub: null);
  @override
  void turnOn(_i5.LightEntity? light) =>
      super.noSuchMethod(Invocation.method(#turnOn, [light]),
          returnValueForMissingStub: null);
  @override
  void onChanged(
          _i6.Entity? entity, dynamic Function(_i5.LightEntity)? onchanged) =>
      super.noSuchMethod(Invocation.method(#onChanged, [entity, onchanged]),
          returnValueForMissingStub: null);
}
