// Mocks generated by Mockito 5.2.0 from annotations
// in homsai/test/util/ai_service/ai_service.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:homsai/business/ai_service/ai_service.interface.dart' as _i5;
import 'package:homsai/datastore/DTOs/remote/ai_service/daily_plan/daily_plan.dto.dart'
    as _i3;
import 'package:homsai/datastore/DTOs/remote/ai_service/daily_plan/daily_plan_body.dto.dart'
    as _i8;
import 'package:homsai/datastore/DTOs/remote/ai_service/forecast/consumption_optimizations/consumption_optimizations_forecast.dto.dart'
    as _i2;
import 'package:homsai/datastore/DTOs/remote/ai_service/forecast/consumption_optimizations/consumption_optimizations_forecast_body.dto.dart'
    as _i7;
import 'package:homsai/datastore/DTOs/remote/ai_service/forecast/photovoltaic/photovoltaic.dto.dart'
    as _i11;
import 'package:homsai/datastore/DTOs/remote/ai_service/forecast/photovoltaic/photovoltaic_body.dto.dart'
    as _i12;
import 'package:homsai/datastore/DTOs/remote/ai_service/forecast/suggestions_chart/suggestions_chart.dto.dart'
    as _i4;
import 'package:homsai/datastore/DTOs/remote/ai_service/login/login_body.dto.dart'
    as _i10;
import 'package:homsai/datastore/models/ai_service_auth.model.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeConsumptionOptimizationsForecastDto_0 extends _i1.Fake
    implements _i2.ConsumptionOptimizationsForecastDto {}

class _FakeDailyPlanDto_1 extends _i1.Fake implements _i3.DailyPlanDto {}

class _FakeSuggestionsChartDto_2 extends _i1.Fake
    implements _i4.SuggestionsChartDto {}

/// A class which mocks [AIServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIServiceInterface extends _i1.Mock
    implements _i5.AIServiceInterface {
  MockAIServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ConsumptionOptimizationsForecastDto>
      getPhotovoltaicSelfConsumptionOptimizerForecast(
              _i7.ConsumptionOptimizationsForecastBodyDto?
                  optimizationsForecastBody,
              String? unit) =>
          (super.noSuchMethod(
              Invocation.method(
                  #getPhotovoltaicSelfConsumptionOptimizerForecast,
                  [optimizationsForecastBody, unit]),
              returnValue: Future<_i2.ConsumptionOptimizationsForecastDto>.value(
                  _FakeConsumptionOptimizationsForecastDto_0())) as _i6
              .Future<_i2.ConsumptionOptimizationsForecastDto>);
  @override
  _i6.Future<_i3.DailyPlanDto> getDailyPlan(
          _i8.DailyPlanBodyDto? dailyPlanBodyDto,
          int? deviceNumber,
          List<String>? entitysType) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getDailyPlan, [dailyPlanBodyDto, deviceNumber, entitysType]),
              returnValue:
                  Future<_i3.DailyPlanDto>.value(_FakeDailyPlanDto_1()))
          as _i6.Future<_i3.DailyPlanDto>);
  @override
  _i6.Future<_i9.AiServiceAuth?> getToken(_i10.LoginBodyDto? loginBodyDto) =>
      (super.noSuchMethod(Invocation.method(#getToken, [loginBodyDto]),
              returnValue: Future<_i9.AiServiceAuth?>.value())
          as _i6.Future<_i9.AiServiceAuth?>);
  @override
  _i6.Future<_i9.AiServiceAuth?> refreshToken(
          _i9.AiServiceAuth? aiServiceAuth) =>
      (super.noSuchMethod(Invocation.method(#refreshToken, [aiServiceAuth]),
              returnValue: Future<_i9.AiServiceAuth?>.value())
          as _i6.Future<_i9.AiServiceAuth?>);
  @override
  _i6.Future<dynamic> subscribeToBeta(_i10.LoginBodyDto? loginBodyDto) =>
      (super.noSuchMethod(Invocation.method(#subscribeToBeta, [loginBodyDto]),
          returnValue: Future<dynamic>.value()) as _i6.Future<dynamic>);
  @override
  _i6.Future<List<_i11.PhotovoltaicForecastDto>> getPhotovoltaicForecast(
          _i12.PhotovoltaicForecastBodyDto? dailyPlanBodyDto) =>
      (super.noSuchMethod(
              Invocation.method(#getPhotovoltaicForecast, [dailyPlanBodyDto]),
              returnValue: Future<List<_i11.PhotovoltaicForecastDto>>.value(
                  <_i11.PhotovoltaicForecastDto>[]))
          as _i6.Future<List<_i11.PhotovoltaicForecastDto>>);
  @override
  _i6.Future<_i4.SuggestionsChartDto> getSuggestionsChart() =>
      (super.noSuchMethod(Invocation.method(#getSuggestionsChart, []),
              returnValue: Future<_i4.SuggestionsChartDto>.value(
                  _FakeSuggestionsChartDto_2()))
          as _i6.Future<_i4.SuggestionsChartDto>);
}
