// Mocks generated by Mockito 5.2.0 from annotations
// in homsai/test/integration/scanner_page/scanner_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:convert' as _i23;

import 'package:connectivity_plus/connectivity_plus.dart' as _i24;
import 'package:homsai/business/home_assistant/home_assistant.repository.dart'
    as _i16;
import 'package:homsai/business/home_assistant_scanner/home_assistant_scanner.repository.dart'
    as _i20;
import 'package:homsai/datastore/dao/configuration.dao.dart' as _i4;
import 'package:homsai/datastore/dao/home_assistant.dao.dart' as _i5;
import 'package:homsai/datastore/dao/plant.dao.dart' as _i3;
import 'package:homsai/datastore/dao/user.dao.dart' as _i2;
import 'package:homsai/datastore/DTOs/remote/history/history.dto.dart' as _i17;
import 'package:homsai/datastore/DTOs/remote/history/history_body.dto.dart'
    as _i18;
import 'package:homsai/datastore/DTOs/remote/logbook/logbook.dto.dart' as _i9;
import 'package:homsai/datastore/DTOs/remote/logbook/logbook_body.dto.dart'
    as _i19;
import 'package:homsai/datastore/local/app.database.dart' as _i11;
import 'package:homsai/datastore/models/database/configuration.entity.dart'
    as _i12;
import 'package:homsai/datastore/models/database/plant.entity.dart' as _i15;
import 'package:homsai/datastore/models/database/user.entity.dart' as _i14;
import 'package:homsai/datastore/models/entity/base/base.entity.dart' as _i13;
import 'package:homsai/datastore/models/home_assistant_auth.model.dart' as _i8;
import 'package:homsai/datastore/remote/network/network.manager.dart' as _i10;
import 'package:homsai/datastore/remote/rest/remote.Interface.dart' as _i21;
import 'package:http/http.dart' as _i22;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserDao_0 extends _i1.Fake implements _i2.UserDao {}

class _FakePlantDao_1 extends _i1.Fake implements _i3.PlantDao {}

class _FakeConfigurationDao_2 extends _i1.Fake implements _i4.ConfigurationDao {
}

class _FakeHomeAssistantDao_3 extends _i1.Fake implements _i5.HomeAssistantDao {
}

class _FakeStreamController_4<T> extends _i1.Fake
    implements _i6.StreamController<T> {}

class _FakeDatabaseExecutor_5 extends _i1.Fake implements _i7.DatabaseExecutor {
}

class _FakeHomeAssistantAuth_6 extends _i1.Fake
    implements _i8.HomeAssistantAuth {}

class _FakeStreamSubscription_7<T> extends _i1.Fake
    implements _i6.StreamSubscription<T> {}

class _FakeUri_8 extends _i1.Fake implements Uri {}

class _FakeLogbookDto_9 extends _i1.Fake implements _i9.LogbookDto {}

class _FakeNetworkManagerSubscribersHandler_10 extends _i1.Fake
    implements _i10.NetworkManagerSubscribersHandler {}

/// A class which mocks [HomsaiDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomsaiDatabase extends _i1.Mock implements _i11.HomsaiDatabase {
  MockHomsaiDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserDao get userDao => (super.noSuchMethod(Invocation.getter(#userDao),
      returnValue: _FakeUserDao_0()) as _i2.UserDao);
  @override
  _i3.PlantDao get plantDao => (super.noSuchMethod(Invocation.getter(#plantDao),
      returnValue: _FakePlantDao_1()) as _i3.PlantDao);
  @override
  _i4.ConfigurationDao get configurationDao =>
      (super.noSuchMethod(Invocation.getter(#configurationDao),
          returnValue: _FakeConfigurationDao_2()) as _i4.ConfigurationDao);
  @override
  _i5.HomeAssistantDao get homeAssitantDao =>
      (super.noSuchMethod(Invocation.getter(#homeAssitantDao),
          returnValue: _FakeHomeAssistantDao_3()) as _i5.HomeAssistantDao);
  @override
  _i6.StreamController<String> get changeListener =>
      (super.noSuchMethod(Invocation.getter(#changeListener),
              returnValue: _FakeStreamController_4<String>())
          as _i6.StreamController<String>);
  @override
  set changeListener(_i6.StreamController<String>? _changeListener) =>
      super.noSuchMethod(Invocation.setter(#changeListener, _changeListener),
          returnValueForMissingStub: null);
  @override
  _i7.DatabaseExecutor get database =>
      (super.noSuchMethod(Invocation.getter(#database),
          returnValue: _FakeDatabaseExecutor_5()) as _i7.DatabaseExecutor);
  @override
  set database(_i7.DatabaseExecutor? _database) =>
      super.noSuchMethod(Invocation.setter(#database, _database),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i12.Configuration?> getConfiguration() =>
      (super.noSuchMethod(Invocation.method(#getConfiguration, []),
              returnValue: Future<_i12.Configuration?>.value())
          as _i6.Future<_i12.Configuration?>);
  @override
  _i6.Future<List<T>> getEntities<T extends _i13.Entity>() =>
      (super.noSuchMethod(Invocation.method(#getEntities, []),
          returnValue: Future<List<T>>.value(<T>[])) as _i6.Future<List<T>>);
  @override
  _i6.Future<void> updatePlant(int? plantId) =>
      (super.noSuchMethod(Invocation.method(#updatePlant, [plantId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<_i14.User?> getUser() =>
      (super.noSuchMethod(Invocation.method(#getUser, []),
          returnValue: Future<_i14.User?>.value()) as _i6.Future<_i14.User?>);
  @override
  _i6.Future<_i15.Plant?> getPlant() =>
      (super.noSuchMethod(Invocation.method(#getPlant, []),
          returnValue: Future<_i15.Plant?>.value()) as _i6.Future<_i15.Plant?>);
  @override
  _i6.Future<T?> getEntity<T extends _i13.Entity>(String? entityId) =>
      (super.noSuchMethod(Invocation.method(#getEntity, [entityId]),
          returnValue: Future<T?>.value()) as _i6.Future<T?>);
  @override
  _i6.Future<void> logout({bool? deleteUser = true}) => (super.noSuchMethod(
      Invocation.method(#logout, [], {#deleteUser: deleteUser}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}

/// A class which mocks [HomeAssistantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeAssistantRepository extends _i1.Mock
    implements _i16.HomeAssistantRepository {
  MockHomeAssistantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i8.HomeAssistantAuth> authenticate(
          {Uri? baseUrl, Uri? fallback}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #authenticate, [], {#baseUrl: baseUrl, #fallback: fallback}),
              returnValue: Future<_i8.HomeAssistantAuth>.value(
                  _FakeHomeAssistantAuth_6()))
          as _i6.Future<_i8.HomeAssistantAuth>);
  @override
  _i6.Future<_i8.HomeAssistantAuth> authenticateHomeAssistant({Uri? url}) =>
      (super.noSuchMethod(
              Invocation.method(#authenticateHomeAssistant, [], {#url: url}),
              returnValue: Future<_i8.HomeAssistantAuth>.value(
                  _FakeHomeAssistantAuth_6()))
          as _i6.Future<_i8.HomeAssistantAuth>);
  @override
  _i6.Future<_i6.StreamSubscription<String>> scan(
          {void Function(String)? onData,
          Function? onError,
          Duration? timeout}) =>
      (super.noSuchMethod(
              Invocation.method(#scan, [],
                  {#onData: onData, #onError: onError, #timeout: timeout}),
              returnValue: Future<_i6.StreamSubscription<String>>.value(
                  _FakeStreamSubscription_7<String>()))
          as _i6.Future<_i6.StreamSubscription<String>>);
  @override
  _i6.Future<Uri> canConnectToHomeAssistant(
          {Uri? baseUrl,
          Uri? fallback,
          Duration? timeout = const Duration(seconds: 2)}) =>
      (super.noSuchMethod(
          Invocation.method(#canConnectToHomeAssistant, [],
              {#baseUrl: baseUrl, #fallback: fallback, #timeout: timeout}),
          returnValue: Future<Uri>.value(_FakeUri_8())) as _i6.Future<Uri>);
  @override
  _i6.Future<_i8.HomeAssistantAuth> refreshToken(
          {Uri? url, Duration? timeout = const Duration(seconds: 2)}) =>
      (super.noSuchMethod(
          Invocation.method(#refreshToken, [], {#url: url, #timeout: timeout}),
          returnValue: Future<_i8.HomeAssistantAuth>.value(
              _FakeHomeAssistantAuth_6())) as _i6
          .Future<_i8.HomeAssistantAuth>);
  @override
  _i6.Future<dynamic> revokeToken(
          {_i15.Plant? plant,
          Duration? timeout = const Duration(seconds: 2)}) =>
      (super.noSuchMethod(
          Invocation.method(
              #revokeToken, [], {#plant: plant, #timeout: timeout}),
          returnValue: Future<dynamic>.value()) as _i6.Future<dynamic>);
  @override
  _i6.Future<List<_i17.HistoryDto>> getHistory(
          {_i15.Plant? plant,
          _i18.HistoryBodyDto? historyBodyDto,
          Duration? timeout = const Duration(seconds: 10)}) =>
      (super.noSuchMethod(
              Invocation.method(#getHistory, [], {
                #plant: plant,
                #historyBodyDto: historyBodyDto,
                #timeout: timeout
              }),
              returnValue:
                  Future<List<_i17.HistoryDto>>.value(<_i17.HistoryDto>[]))
          as _i6.Future<List<_i17.HistoryDto>>);
  @override
  _i6.Future<_i9.LogbookDto> getLogBook(
          {_i15.Plant? plant,
          DateTime? start,
          _i19.LogbookBodyDto? logbookBodyDto}) =>
      (super.noSuchMethod(
              Invocation.method(#getLogBook, [], {
                #plant: plant,
                #start: start,
                #logbookBodyDto: logbookBodyDto
              }),
              returnValue: Future<_i9.LogbookDto>.value(_FakeLogbookDto_9()))
          as _i6.Future<_i9.LogbookDto>);
}

/// A class which mocks [HomeAssistantScannerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeAssistantScannerRepository extends _i1.Mock
    implements _i20.HomeAssistantScannerRepository {
  MockHomeAssistantScannerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<String> scanNetwork({Duration? timeout}) => (super.noSuchMethod(
      Invocation.method(#scanNetwork, [], {#timeout: timeout}),
      returnValue: Stream<String>.empty()) as _i6.Stream<String>);
  @override
  _i6.Future<Uri?> canConnectToHomeAssistant(
          {Uri? url, Duration? timeout = const Duration(seconds: 2)}) =>
      (super.noSuchMethod(
          Invocation.method(
              #canConnectToHomeAssistant, [], {#url: url, #timeout: timeout}),
          returnValue: Future<Uri?>.value()) as _i6.Future<Uri?>);
}

/// A class which mocks [RemoteInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteInterface extends _i1.Mock implements _i21.RemoteInterface {
  MockRemoteInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> parseResponse(_i22.Response? response) =>
      (super.noSuchMethod(Invocation.method(#parseResponse, [response]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  _i6.Future<Map<String, dynamic>> get(Uri? url,
          {Map<String, String>? headers,
          Duration? timeout,
          Uri? fallbackUrl}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [
                url
              ], {
                #headers: headers,
                #timeout: timeout,
                #fallbackUrl: fallbackUrl
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  _i6.Future<Map<String, dynamic>> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding,
          Duration? timeout,
          Uri? fallbackUrl}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                url
              ], {
                #headers: headers,
                #body: body,
                #encoding: encoding,
                #timeout: timeout,
                #fallbackUrl: fallbackUrl
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  _i6.Future<Map<String, dynamic>> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding,
          Duration? timeout,
          Uri? fallbackUrl}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                url
              ], {
                #headers: headers,
                #body: body,
                #encoding: encoding,
                #timeout: timeout,
                #fallbackUrl: fallbackUrl
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
  @override
  _i6.Future<Map<String, dynamic>> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i23.Encoding? encoding,
          Duration? timeout,
          Uri? fallbackUrl}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                url
              ], {
                #headers: headers,
                #body: body,
                #encoding: encoding,
                #timeout: timeout,
                #fallbackUrl: fallbackUrl
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [NetworkManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkManager extends _i1.Mock implements _i10.NetworkManager {
  MockNetworkManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.NetworkManagerSubscribersHandler get subscribersHandler =>
      (super.noSuchMethod(Invocation.getter(#subscribersHandler),
              returnValue: _FakeNetworkManagerSubscribersHandler_10())
          as _i10.NetworkManagerSubscribersHandler);
  @override
  set subscribersHandler(
          _i10.NetworkManagerSubscribersHandler? _subscribersHandler) =>
      super.noSuchMethod(
          Invocation.setter(#subscribersHandler, _subscribersHandler),
          returnValueForMissingStub: null);
  @override
  void subscribe(_i10.NetworkManagerSubscriber? subscriber) =>
      super.noSuchMethod(Invocation.method(#subscribe, [subscriber]),
          returnValueForMissingStub: null);
  @override
  void unsubscribe(_i10.NetworkManagerSubscriber? subscriber) =>
      super.noSuchMethod(Invocation.method(#unsubscribe, [subscriber]),
          returnValueForMissingStub: null);
  @override
  _i6.Future<bool> isConnect() =>
      (super.noSuchMethod(Invocation.method(#isConnect, []),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<_i24.ConnectivityResult> getConnectionType() =>
      (super.noSuchMethod(Invocation.method(#getConnectionType, []),
              returnValue: Future<_i24.ConnectivityResult>.value(
                  _i24.ConnectivityResult.bluetooth))
          as _i6.Future<_i24.ConnectivityResult>);
}
